<?php

class AdminThemeApertus extends AdminTheme implements Module, ConfigurableModule {

	public static function getModuleInfo() {
		return array(
			'title' => 'Apertus Admin Theme',
			'version' => 1,
			'summary' => 'Minimal admin theme that supports all ProcessWire features.',
			'autoload' => 'template=admin'
			); 
	}

	public function init() {
		parent::init(); 
		if($this->isCurrent()) {
			// this is the current admin theme
		}
	}

	public function ___install() {
		parent::___install();
	}

	public static function getModuleConfigInputfields(array $data) {
		$inputfields = new InputfieldWrapper();

		$field = wire('modules')->get('InputfieldText');
		$field->name = 'sitename';
		$field->label = "Enter the name of your site";
		if(isset($data['sitename'])) $field->value = $data['sitename'];
		$inputfields->add($field);

		$field = wire('modules')->get('InputfieldText');
		$field->name = 'color';
		$field->label = "Apertus main color";
		if(isset($data['color'])) $field->value = $data['color'];
		$inputfields->add($field);

		$field = wire('modules')->get('InputfieldRadios');
		$field->attr('name', 'environmentindicator');
		$field->label = __('Environment Indicator');
		$field->addOption('none', __('None'));
		$field->addOption('Production', __('Production'));
		$field->addOption('Staging', __('Staging'));
		$field->addOption('Development', __('Development'));
		$field->attr('value', isset($data['environmentindicator']) ? $data['environmentindicator'] : 'none');
		$field->optionColumns = 1;
		$inputfields->add($field);

		return $inputfields;
	}
}

