<?php

class AdminThemeApertus extends AdminTheme implements Module, ConfigurableModule {

	public static function getModuleInfo() {
		return array(
			'title' => 'Apertus Admin Theme',
			'version' => 1,
			'summary' => 'Minimal admin theme that supports all ProcessWire features.',
			'autoload' => 'template=admin'
			); 
	}

	public function init() {
		parent::init(); 
		if($this->isCurrent()) {
			// this is the current admin theme
		}
	}

	public function ___install() {
		parent::___install();
	}

	public static function getModuleConfigInputfields(array $data) {

	}
}

