<?php

class AdminThemeApertus extends AdminTheme implements Module, ConfigurableModule {

	public static function getModuleInfo() {
		return array(
			'title' => 'Apertus Admin Theme',
			'version' => 1,
			'summary' => 'Minimal admin theme that supports all ProcessWire features.',
			'autoload' => 'template=admin'
			); 
	}

	public function init() {
		parent::init(); 
		if($this->isCurrent()) {
			// this is the current admin theme
		}
	}

	public function ___install() {
		parent::___install();
	}

	public static function getModuleConfigInputfields(array $data) {
		$inputfields = new InputfieldWrapper();
		$field = wire('modules')->get('InputfieldRadios');
		$field->attr('name', 'environment-indicator');
		$field->label = __('Environment Indicator');
		$field->addOption('none', __('None'));
		$field->addOption('production', __('Production'));
		$field->addOption('staging', __('Staging'));
		$field->addOption('development', __('Development'));
		$field->attr('value', isset($data['environment-indicator']) ? $data['environment-indicator'] : 'none');
		$field->optionColumns = 1;
		$inputfields->add($field);
		return $inputfields;
	}
}

